### PR TITLE
We don’t want to error on a notice, for example

### PR DESCRIPTION
**Pull request by scottmcmurray**

### CODE REVIEW

**Comment by samnotsowise** [comment]
There's already provision for this using the `error_reporting` php setting/function. But if you're going to add this in, I don't think it should change existing behavior since errors being thrown for warnings etc may be relied upon in some projects.

**Comment by acuthbert** [comment]
Hmm, i'd be hard pressed to think of an example where we're relying on catching a warning through the error handler. But I agree this change needs tested on other projects maybe before we pull in. I suppose the question is whether we treat warnings as errors - and perhaps let notices slip past?

**Comment by scottmcmurray** [comment]
The problem is, notices and warnings are being thrown as errors by this error handler currently. `error_reporting` isn't really related - for example, turning off notices isn't a solution. We still want those logged. We just don't want them to cause an `ErrorException` to be thrown.

If unhandled by the application, an `ErrorException` can (should) result in a 500 and stop execution. A Notice shouldn't stop execution. 

I agree testing should be done though, incase other projects aren't handling this properly.

**Comment by samnotsowise** [comment]
Ah - error logging was one of the areas I was worried might be affected by this (when using custom loggers we'd still want those to log warnings etc). That's an important feature to check doesn't rely on this behavior.

**Comment by scottmcmurray** [comment]
@acuthbert I looked at which codes should stop execution according to the manual. Warnings specifically state:
> Run-time warnings (non-fatal errors). Execution of the script is not halted.

I also came across this after doing it, which is similar:
http://php.net/manual/en/class.errorexception.php#95415

**Comment by acuthbert** [comment]
Am I right that presently with this change notices and warnings would not come to the RhubarbLog as the ExceptionHandler wouldn't be triggered? @samnotsowise do we care? Do we ever use the Rhubarb log to review these? I'm thinking we probably don't as they should end up in the PHP log anyways?

**Comment by samnotsowise** [comment]
I don't in any of the project's I've worked on, but I am aware of projects which use rhubarb logging much more. I don't know if such projects are relying on this. I guess there's no problem with changing the default behavior when it's a correction like this, so long as there's a way for anywhere that was using it to change it back - which is maybe just be a deprecated filter array which we can remove in the next major version.

**Pull request merged**
